[workspace]
resolver = "2"
members = [
    "runtime",
    "prover",
]
default-members = [
    "runtime",
    "prover",
]

[workspace.package]
edition = "2021"
version = "0.2.3"
authors = ["The Nexus Team <hello@nexus.xyz>"]
homepage = "https://nexus.xyz/"
repository = "https://github.com/nexus-xyz/nexus-zkvm/"
keywords = ["nexus", "zero-knowledge", "zkvm", "cryptography", "proofs"]
categories = ["cryptography"]
publish = false

[workspace.dependencies]
clap = { version = "4.3", features = ["derive"] }
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "f7871979e6ea8e606dc4674301b7d8b28b5838ed" }

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
inherits = "release"
debug = true
