[package]
name = "nexus-rt-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3.1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
tempfile = {version = "3"}

[[test]]
name = "macro_expansion_tests"
path = "macro_expansion_tests/test.rs"

[features]
default = []


