[package]
name = "nexus-vm-prover"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
num-traits = { workspace = true }
stwo-prover = { workspace = true }

[dev-dependencies]
array2d = "0.3.2"
bincode = "1.3"
byte-unit = "5.1"
clap = { workspace = true }
humantime = "2.1"
itertools = "0.13.0"
serde = { workspace = true }
shh = "1.0.1"
