[package]
name = "nexus-vm-prover"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
num-traits = { workspace = true }
stwo-prover = { workspace = true }

[dev-dependencies]
bincode = "1.3"
byte-unit = "5.1"
clap = { workspace = true }
humantime = "2.1"
serde = { workspace = true }
