[package]
name = "nexus-precompile-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
nexus-common = { path = "../../common" }
quote = "1.0"
proc-macro2 = "1.0"
serde = "1.0"
serde_json = "1.0"
syn = { version = "2.0", features = ["full", "parsing"] }
