name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - main

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-01-04
      - run: cargo fmt --all --check
      - run: cd prover-benches && cargo fmt --check

  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
          targets: riscv32i-unknown-none-elf
      - run: echo "RUSTFLAGS=-D warnings" >> $GITHUB_ENV
      - run: cargo check --all-features --all-targets
      - run: cargo check --all-features --examples
      - run: cd prover-benches && cargo check --benches

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: nightly-2024-01-04
          targets: riscv32i-unknown-none-elf
      - run: cargo clippy --no-deps --all-targets --all-features

  test:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
          targets: riscv32i-unknown-none-elf

      - name: Install cargo-expand
        run: cargo install cargo-expand --locked --version 1.0.95 # blocked on upgrading rust; might involve upgrading stwo-prover

      - name: Add RISC-V target
        run: rustup target add riscv32i-unknown-none-elf

      - run: cargo test -r --all --all-features
        timeout-minutes: 30
