name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - main

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-01-04
      - run: cargo fmt --all --check

  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - run: cargo check --all-features --all-targets
      - run: cargo check --all-features --examples

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: nightly-2024-01-04
      - run: cargo clippy --no-deps --all-targets --all-features

  test:
    needs: check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04

      - name: Install cargo-expand
        run: cargo install cargo-expand

      - name: Add RISC-V target
        run: rustup target add riscv32i-unknown-none-elf

      - run: cargo test -r --all-features
      - run: cargo test --package nexus-rt-macros --test macro_expansion_tests test_expansion --features testing
